#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifndef PLATFORM_XBOX360
#include "data_win.h"
#endif

// Loads and caches HLSL9 shader source from SHADERS.BIN (generated by the preprocessor).
// Provides a lookup function that returns translated HLSL9 source for a given shader.

// Initialize the shader cache from SHADERS.BIN data.
// Must be called before any shader lookups.
// The data is copied internally; the caller retains ownership of the buffer.
void ShaderLoader_init(const uint8_t* data, size_t size);

// Look up the translated HLSL9 vertex shader source for a shader by index in the SHDR chunk.
// Returns NULL if not found or if the entry has no data.
const char* ShaderLoader_getVertexSource(uint32_t shaderIndex);

// Look up the translated HLSL9 fragment/pixel shader source for a shader by index in the SHDR chunk.
// Returns NULL if not found or if the entry has no data.
const char* ShaderLoader_getFragmentSource(uint32_t shaderIndex);

// Returns true if the shader cache has been initialized and contains data.
bool ShaderLoader_hasData(void);

// Frees all cached shader data.
void ShaderLoader_shutdown(void);