//
// Shader Loader for D3D9 Renderer (Xbox 360)
//
// Loads and caches HLSL9 shader source from SHADERS.BIN (generated by
// the preprocessor's ShaderProcessor), and provides lookup functions
// so the D3D9 renderer can use translated shaders.
//
// SHADERS.BIN format:
//   uint8_t  version (0)
//   uint16_t shaderCount
//   (for each shader:)
//     uint8_t  nameLen
//     char[]   name (nameLen bytes)
//     uint8_t  type (0=vertex, 1=fragment)
//     uint32_t hlslLen
//     char[]   hlslSource (hlslLen bytes)
//
// The entries are indexed 0..shaderCount-1, with vertex at even indices
// (shaderIndex*2) and fragment at odd indices (shaderIndex*2+1).
//

#include "shader_loader.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef struct {
    char* name;       // owned
    char* hlslSource; // owned HLSL9 source
    size_t hlslLen;
    bool isVertex;
    bool valid;
} ShaderCacheEntry;

static ShaderCacheEntry* g_shaderEntries = NULL;
static uint32_t g_shaderEntryCount = 0;
static bool g_initialized = false;

void ShaderLoader_init(const uint8_t* data, size_t size) {
    ShaderLoader_shutdown();

    if (!data || size < 3) return;

    // Parse header
    uint8_t version = data[0];
    if (version != 0) {
        fprintf(stderr, "ShaderLoader: Unknown version %d\n", version);
        return;
    }

    uint16_t shaderCount = (uint16_t)(data[1] | (data[2] << 8));
    if (shaderCount == 0) return;

    // Each shader has 2 entries (vertex + fragment), so total entries = shaderCount * 2
    g_shaderEntryCount = shaderCount * 2;
    g_shaderEntries = (ShaderCacheEntry*)calloc(g_shaderEntryCount, sizeof(ShaderCacheEntry));
    if (!g_shaderEntries) return;

    size_t offset = 3; // skip header
    uint32_t entryIdx = 0;

    for (uint32_t i = 0; i < shaderCount && offset < size; i++) {
        // Read vertex entry
        if (entryIdx < g_shaderEntryCount && offset < size) {
            ShaderCacheEntry* entry = &g_shaderEntries[entryIdx];

            // Read name
            uint8_t nameLen = data[offset++];
            if (nameLen > 0 && offset + nameLen <= size) {
                entry->name = (char*)malloc(nameLen + 1);
                if (entry->name) {
                    memcpy(entry->name, &data[offset], nameLen);
                    entry->name[nameLen] = '\0';
                }
                offset += nameLen;
            }

            // Read type (should be 0 for vertex)
            uint8_t type = data[offset++];
            entry->isVertex = (type == 0);

            // Read HLSL source
            if (offset + 4 <= size) {
                uint32_t hlslLen = (uint32_t)(data[offset] | (data[offset+1] << 8) | (data[offset+2] << 16) | (data[offset+3] << 24));
                offset += 4;
                if (hlslLen > 0 && offset + hlslLen <= size) {
                    entry->hlslSource = (char*)malloc(hlslLen + 1);
                    if (entry->hlslSource) {
                        memcpy(entry->hlslSource, &data[offset], hlslLen);
                        entry->hlslSource[hlslLen] = '\0';
                        entry->hlslLen = hlslLen;
                        entry->valid = true;
                    }
                    offset += hlslLen;
                }
            }
            entryIdx++;
        }

        // Read fragment entry
        if (entryIdx < g_shaderEntryCount && offset < size) {
            ShaderCacheEntry* entry = &g_shaderEntries[entryIdx];

            // Read name
            uint8_t nameLen = data[offset++];
            if (nameLen > 0 && offset + nameLen <= size) {
                entry->name = (char*)malloc(nameLen + 1);
                if (entry->name) {
                    memcpy(entry->name, &data[offset], nameLen);
                    entry->name[nameLen] = '\0';
                }
                offset += nameLen;
            }

            // Read type (should be 1 for fragment)
            uint8_t type = data[offset++];
            entry->isVertex = (type == 0);

            // Read HLSL source
            if (offset + 4 <= size) {
                uint32_t hlslLen = (uint32_t)(data[offset] | (data[offset+1] << 8) | (data[offset+2] << 16) | (data[offset+3] << 24));
                offset += 4;
                if (hlslLen > 0 && offset + hlslLen <= size) {
                    entry->hlslSource = (char*)malloc(hlslLen + 1);
                    if (entry->hlslSource) {
                        memcpy(entry->hlslSource, &data[offset], hlslLen);
                        entry->hlslSource[hlslLen] = '\0';
                        entry->hlslLen = hlslLen;
                        entry->valid = true;
                    }
                    offset += hlslLen;
                }
            }
            entryIdx++;
        }
    }

    g_initialized = true;
}

const char* ShaderLoader_getVertexSource(uint32_t shaderIndex) {
    if (!g_initialized || !g_shaderEntries) return NULL;

    uint32_t entryIdx = shaderIndex * 2;
    if (entryIdx >= g_shaderEntryCount) return NULL;

    ShaderCacheEntry* entry = &g_shaderEntries[entryIdx];
    if (!entry->valid || !entry->isVertex) return NULL;

    return entry->hlslSource;
}

const char* ShaderLoader_getFragmentSource(uint32_t shaderIndex) {
    if (!g_initialized || !g_shaderEntries) return NULL;

    uint32_t entryIdx = shaderIndex * 2 + 1;
    if (entryIdx >= g_shaderEntryCount) return NULL;

    ShaderCacheEntry* entry = &g_shaderEntries[entryIdx];
    if (!entry->valid || entry->isVertex) return NULL;

    return entry->hlslSource;
}

bool ShaderLoader_hasData(void) {
    return g_initialized && g_shaderEntries && g_shaderEntryCount > 0;
}

void ShaderLoader_shutdown(void) {
    if (g_shaderEntries) {
        for (uint32_t i = 0; i < g_shaderEntryCount; i++) {
            free(g_shaderEntries[i].name);
            free(g_shaderEntries[i].hlslSource);
        }
        free(g_shaderEntries);
        g_shaderEntries = NULL;
    }
    g_shaderEntryCount = 0;
    g_initialized = false;
}